# Generated by Django 5.0 on 2023-12-15 17:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Add Image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='contet',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
